spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres


  flyway:
    baseline-on-migrate: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  sql:
    init:
      mode: always


logging:
  level:
    org:
      springframework:
        security: DEBUG